query allPeopleQuery($first: Int!, $after: String!){
    allPeople(first: $first, after: $after){
                people{
                name
                species {
                    name
                }
                homeworld {
                    name
                }
                eyeColor
                hairColor
                skinColor
                birthYear
                vehicleConnection{
                    vehicles{
                    name
                    }
                }

                }

                pageInfo {
                    endCursor
                }
            }
}